import { NextApiRequest, NextApiResponse } from "next";

const adu =[
    {id:1, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Beden Ağırlığının Denetimi"},
    {id:3, sinif:3, uni:"adu", ders:"Hastalıklar Diyet 1",konu:"Obezitede Medikal Beslenme Tedavisi"},
    {id:4, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Yeme Davranışı Bozukluklarında Beslenme Tedavisi"},
    {id:5, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Diabetes Mellitus"},
    {id:6, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Ağız-Özafagus-Mide Hastalıklar ve Beslenme"},
    {id:7, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Kalp-Damar Hastalıkları, Hipertansiyon ve Beslenme"},
    {id:14, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Canlılık Öğretisinin On Teması"},
    {id:15, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Canlıların Kimyasal İçeriği"},
    {id:16, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Su ve Çevrenin Canlılar İçin Uygunluğu"},
    {id:17, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Karbon ve Canlılardaki Molekül Çeşitliliği"},
    {id:18, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Makromoleküllerin Yapı ve İşlevleri"},
    {id:19, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"Kan Fizyolojisi ve Patolojisi"},
    {id:20, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"Fizyoloji Giriş"},
    {id:21, sinif:2, uni:"adu", ders:"Fİzyopatoloji",konu:"Apoptosis"},
    {id:23, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"Endokrin Sistem Hastalıkları"},
    {id:24, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"GİS Hastalıkları"},
    {id:25, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"İmmün Sistem"},
    {id:26, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"KVS Fizyopatolojisi"},
    {id:27, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"Sinir Sistemi Fizyopatolojisi"},
    {id:28, sinif:2, uni:"adu", ders:"Fizyopatoloji",konu:"Solunum Fizyopatolojisi"},
    {id:29, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Aminoasitlerin Biyosentezi"},
    {id:30, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Aminoasitlerin Yıkılımı"},
    {id:31, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Hücre"},
    {id:32, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Hücre Sinyal İletimi"},
    {id:33, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Karbonhidratlar"},
    {id:34, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Keton Cisimleri"},
    {id:35, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Kolestrol Metabolizması"},
    {id:36, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Lipid ve Lipoprotein Metabolizması"},
    {id:37, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Malat Aspartat"},
    {id:38, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Yağ Asidi Yıkımı"},
    {id:39, sinif:2, uni:"adu", ders:"Biyokimya",konu:"Yağ Asidi Sentezi"},
    {id:40, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Perbiyotikler"},
    {id:41, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Probiyotikler"},
    {id:42, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Diyabet ve Mikrobiyota"},
    {id:43, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"İnflamatuar Bağırsak Hastalıkları"},
    {id:44, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Kanser ve Miktobiyota"},
    {id:45, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Obezite ve Mikrobiyota"},
    {id:46, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"1. Hafta"},
    {id:47, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"2. Hafta"},
    {id:48, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"5. Hafta"},
    {id:49, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"6. Hafta"},
    {id:50, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"7. Hafta"},
    {id:51, sinif:3, uni:"adu", ders:"Spor ve Beslenme",konu:"8. Hafta"},
    {id:52, sinif:3, uni:"adu", ders:"TBS",konu:"Toplu Beslenmenin Tanımı, Önemi ve Toplu Beslenme Yapılan Kuruluşların Özellikleri"},
    {id:53, sinif:1, uni:"adu", ders:"Beslenme İlkeleri",konu:"Beslenmeye Genel Bakış"},
    {id:54, sinif:1, uni:"adu", ders:"Beslenme İlkeleri",konu:"Karbonhidratlar"},
    {id:55, sinif:1, uni:"adu", ders:"Beslenme İlkeleri",konu:"Tahıllar"},
    {id:56, sinif:1, uni:"adu", ders:"Beslenme İlkeleri",konu:"Şeker, Bal, Pekmez, Tatlandırıcılar"},
    {id:57, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Metabolizmaya Giriş"},
    {id:58, sinif:1, uni:"adu", ders:"Genel Bİyoloji",konu:"Hücre İçine Yolculuk"},
    {id:59, sinif:1, uni:"adu", ders:"Genel Biyoloji",konu:"Zar Yapısı ve İşlevi"},
    {id:60, sinif:3, uni:"adu", ders:"TBS",konu:"TBS'de Yönetim ve Organizasyon"},
    {id:61, sinif:3, uni:"adu", ders:"TBS",konu:"TBS Yapılan Kurumlarda Mutfak ve Yemekhane Planlaması"},
    {id:62, sinif:3, uni:"adu", ders:"TBS",konu:"Kurum Beslenme Servislerinde Yemek Planlama ve Tarife Standartlaştırma"},
    {id:63, sinif:3, uni:"adu", ders:"TBS",konu:"Yemek Çeşitleri"},
    {id:64, sinif:3, uni:"adu", ders:"TBS",konu:"Ana Yemek ve Tatlılar"},
    {id:65, sinif:3, uni:"adu", ders:"TBS",konu:"Yemek Sofrası"},
    {id:67, sinif:3, uni:"adu", ders:"TBS",konu:"Yiyecekleri Satın Alma ve Depolama"},
    {id:68, sinif:3, uni:"adu", ders:"TBS",konu:"Yiyeceklerin Hazırlanması ve Pişirilmesi"},
    {id:69, sinif:3, uni:"adu", ders:"TBS",konu:"TBS'de Ticari İşletmeler"},
    {id:70, sinif:3, uni:"adu", ders:"TBS",konu:"Toplu Beslenme Sistemlerinde Hijyen"},
    {id:71, sinif:3, uni:"adu", ders:"TBS",konu:"TBS Yapılan Kurumlarda Mutfak ve Yemekhane Temizliği"},
    {id:72, sinif:3, uni:"adu", ders:"TBS",konu:"Toplu Beslenme Yapılan Kuruluşlarda Kalite Yönetim Sistemi"},
    {id:73, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Diyabette Beslenme"},
    {id:74, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Alkolizm, Safra ve Pankreas Hastalıkları"},
    {id:75, sinif:3, uni:"adu", ders:"hastalıklarda Diyet 1",konu:"GİS Hastalıklarında Beslenme"},
    {id:76, sinif:3, uni:"adu", ders:"Hastalıklarda Diyet 1",konu:"Karaciğer Hastalıkları"},
    {id:78, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Modern Tıpta Prebiyotikler ve Probiyotikler"},
    {id:80, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Mikrobiyota, Fetal Yaşam, Erken Çocukluk Dönemi ve Çocuk Sağlığıa Etkisi"},
    {id:81, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Prebiyotik, Probiyotik ve Sinbiyotiklerin Kısa ve Uzun Dönemde Tokluk ve Besin Tüketimi Üzerine Etkisi"},
    {id:82, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Probiyotik, Prebiyotik ve Sinbiyotikler"},
    {id:83, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Probiyotikler, Prebiyotikler ve Sinbiyotikler 2"},
    {id:85, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Probiyotikler ve Prebiyotiklerin Sağlık Üzerine Etkileri"},
    {id:86, sinif:3, uni:"adu", ders:"AÇS",konu:"Gebelik Döneminde Beslenme"},
    {id:87, sinif:3, uni:"adu", ders:"AÇS",konu:"Anne Sütü"},
    {id:88, sinif:3, uni:"adu", ders:"AÇS",konu:"0-1 Yaş Beslenmesi"},
    {id:89, sinif:3, uni:"adu", ders:"AÇS",konu:"Emiziklilik Döneminde Beslenme"},
    {id:90, sinif:3, uni:"adu", ders:"AÇS",konu:"Çocukluk Çağı (Okul Öncesi ve Okul Çağı) Beslenmesi"},
    {id:91, sinif:3, uni:"adu", ders:"AÇS",konu:"Adölesan Çağı Beslenmesi"},
    {id:92, sinif:3, uni:"adu", ders:"AÇS",konu:"Türkiye'de Çocuk Beslenmesi ve Önemi"},
    {id:93, sinif:3, uni:"adu", ders:"AÇS",konu:"Mamalar"},
    {id:94, sinif:3, uni:"adu", ders:"AÇS",konu:"Prematüre Bebeklerde Beslenme"},
    {id:95, sinif:3, uni:"adu", ders:"AÇS",konu:"Protein-Enerji Malnutrisyonu (PEM) ve Beslenme Tedavisi"},
    {id:96, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Mikro Besin Ögeleri ve Mikrobiyotaya Etkileri"},
    {id:97, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Egzersizin Bağırsak Mikrobiyotasına Etkileri"},
    {id:98, sinif:2, uni:"adu", ders:"Probiyotikler ve Sağlık",konu:"Nörolojik Hastalıklar ve Mikrobiyota"},
    {id:99, sinif:3, uni:"adu", ders:"Beslenme Eğitimi",konu:"Beslenme Eğitimi"},
    {id:100, sinif:3, uni:"adu", ders:"Beslenme Eğitimi",konu:"Toplumdaki Beslenme Sorunlarının Nedenleri"},
    {id:101, sinif:3, uni:"adu", ders:"Beslenme Eğitimi",konu:"Beslenme Eğitimi Neden Önemli"},
    {id:102, sinif:3, uni:"adu", ders:"Beslenme Eğitimi",konu:"Beslenmenin Toplum Sağlığındaki Yeri ve Önemi"},
    {id:103, sinif:3, uni:"adu", ders:"Beslenme Eğitimi",konu:"Toplumda Beslenme Sorunlarının Saptanmasında Yöntemler"},
    
]

export default function (req:NextApiRequest,res:NextApiResponse){
    if(req.method=="POST"){
        const {uni}=req.body;
        if(uni=="adu"){
            res.json(adu);
        }
    }

}